# -*- mode: makefile; -*-

# contrib/epm-pkg/Makefile
# Build packages with epm program.
# All the config files are in: contrib/epm-pkg/

# To use always reference the contrib/epm-pkg/Makefile
# make -f contrib/epm-pkg/Makefile.pkg TARGET


# --------------------
# Macros
SHELL=/bin/bash
mRsyncOpt = -azP

include ver.mak

# --------------------
# Manual Targets

help : check-top
	@echo -e "\nalias pkg='make -f contrib/epm-pkg/Makefile.pkg'"
	@echo -e "\nInitialize"
	@echo -e '\tpkg config\n'
	@echo -e "Build the pseudo root dist/"
	@echo -e "\tpkg build\n"
	@echo -e "Create the package. Put it in pkg/"
	@echo -e "\tpkg package"

clean :
	find . -type f -name '*~' -exec rm {} \;

dist-clean :  check-top clean
	rm -rf dist pkg

config configure : check-top check-deps ver.mak
	./autogen.sh
	./configure --prefix=$$PWD/dist/usr/local

build : check-top configure dist ver.env
	make
	make install
	make html
	-mkdir -p dist/usr/local/share/rsnapshot
	cp -r docs/* dist/usr/local/share/rsnapshot
	cp COPYING dist/usr/local/share/rsnapshot
	mv rsnapshot.html dist/usr/local/share/rsnapshot
	grep PRETTY_NAME /etc/lsb-release >dist/usr/local/share/rsnapshot/build-os
	uname -a >>dist/usr/local/share/rsnapshot/build-os

package : build pkg ver.epm

release : save ver.env

save :
	git pull origin develop
	git commit -am Updated
	git push origin develop

# --------------------
# Rules

check-top :
	@if [[ ! -d contrib ]]; then \
		echo "You are not in the top dir."; \
		exit 1;  \
	fi

check-deps :
	command -v epm
	command -v epm-patch
	command -v git
	command -v mkepmlist
	command -v mkver.pl
	command -v perl
	command -v rsync

dist pkg :
	mkdir $@

ver.mak ver.env ver.epm : ver.sh
	export RELEASE=1; mkver.pl -e 'mak env epm'
