# contrib/epm-pkg/Makefile
# Build packages with epm program.
# All the config files are in: contrib/epm-pkg/

# To use always reference the contrib/epm-pkg/Makefile
# make -f contrib/epm-pkg/Makefile TARGET

# make config
# make build - build the pseudo root dist/
# make package - create the package. Put it in pkg/
